In [4]:


# Face Recognition

# Importing the libraries



import cv2
from keras.models import load_model
import numpy as np
from PIL import Image

model = load_model('facefeatures_new_model.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image

    # gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)

    if faces == ():
        return None

    # Crop all faces found
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 255), 2)
        cropped_face = img[y:y + h, x:x + w]

    return cropped_face


# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    # canvas = detect(gray, frame)
    # image, face =face_detector(frame)

    face = face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
        # Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
        # Our keras model used a 4D tensor, (images x height x width x channel)
        # So changing dimension 128x128x3 into 1x128x128x3
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)

        name = "None matching"

        if (pred[0][1] > 0.5):
            name = 'Mayuri'
            cv2.putText(frame, name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
        elif (pred[0][0] > 0.5):
            name = 'Jayashree'
            cv2.putText(frame, name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
            
    else:
        cv2.putText(frame, "No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()





<ipython-input-4-ba3fa77c7a39>:25: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if faces == ():


[[5.7603333e-38 1.0000000e+00]]
[[8.5333773e-16 1.0000000e+00]]
[[0. 1.]]
[[1.000000e+00 2.503742e-21]]
[[9.999988e-01 1.215950e-06]]
[[0.00829885 0.9917012 ]]
[[1.0000000e+00 5.3390314e-09]]
[[0.5694378  0.43056223]]
[[2.4666142e-13 1.0000000e+00]]
[[1.5193834e-06 9.9999845e-01]]
[[9.9999952e-01 4.5692403e-07]]
[[1.000000e+00 2.279741e-16]]
[[1.0000000e+00 7.3386664e-21]]
[[1.0000000e+00 6.2680495e-21]]
[[1.000000e+00 3.873974e-18]]
[[0.9029119  0.09708805]]
[[1.0000000e+00 3.5781135e-11]]
[[9.99885559e-01 1.14409595e-04]]
[[1.0000000e+00 7.7822046e-19]]
[[1.000000e+00 6.128909e-19]]
[[1.0000000e+00 4.8579016e-26]]
[[9.999962e-01 3.839706e-06]]
[[1.000000e+00 2.191641e-08]]
[[3.7366557e-16 1.0000000e+00]]
[[2.9270742e-11 1.0000000e+00]]
[[3.6647905e-22 1.0000000e+00]]
[[1.679967e-07 9.999999e-01]]
[[6.269897e-34 1.000000e+00]]
[[2.6611963e-21 1.0000000e+00]]
[[0. 1.]]
